### ISSUE TITLE
Deploy site to docs.status.network

### ISSUE THREAD

**Issue by nadeemb53** [status-im/status-network-docs#1]
### Site Details
- **Type**: Static site (Docusaurus)
- **Domain**: docs.status.network
- **Source**: https://github.com/status-im/status-network-docs/tree/main

### Requirements
- Static file hosting
- HTTPS required
- Standard Node.js build environment
- Build command: `yarn build`

### Deadline
31st Oct 2024

**Comment by siddarthkay** [comment]
@jakubgs : I can take care of this

**Comment by jakubgs** [comment]
No, focus on your current tasks.

**Comment by markoburcul** [comment]
@nadeemb53 do you guys need also a `dev.docs.status.network` which would be built based on the `develop` branch?

**Comment by nadeemb53** [comment]
@markoburcul that'll be great to have!

**Comment by nadeemb53** [comment]
@markoburcul we won't need it since the docs won't be updated much

**Comment by nadeemb53** [comment]
> Then the site has been deployed on docs.status.network and it will be updated on pushes to the master branch.

That's great @markoburcul . I pushed an update to `master` 20 minutes ago. It's not updated yet. Does it need time or subsequent commits will be deployed?

**Comment by markoburcul** [comment]
> That's great [@markoburcul](https://github.com/markoburcul) . I pushed an update to `master` 20 minutes ago. It's not updated yet. Does it need time or subsequent commits will be deployed?

It should be updated since I see in the logs on the server an update did arrive, have you tried refreshing browser?

**Comment by nadeemb53** [comment]
> It should be updated since I see in the logs on the server an update did arrive, have you tried refreshing browser?

yes, the new content hasn't shown up yet

**Comment by markoburcul** [comment]
> yes, the new content hasn't shown up yet

You accidentally removed a [line](https://github.com/status-im/status-network-docs/commit/7a9a7f56d95565263d9e98385f78871235681c27) from my [commit](https://github.com/status-im/status-network-docs/blob/640798f1adb257ad425aed58b9d9e43f3fc8f1d3/Jenkinsfile#L49) which resulted in[ failed build of site](https://ci.infra.status.im/job/website/job/docs.status.network/24/). Please return it and it will work.

**Comment by nadeemb53** [comment]
> You accidentally removed (from my [commit](https://github.com/status-im/status-network-docs/commit/7a9a7f56d95565263d9e98385f78871235681c27)) a [line](https://github.com/status-im/status-network-docs/blob/640798f1adb257ad425aed58b9d9e43f3fc8f1d3/Jenkinsfile#L49) which resulted in[ failed build of site](https://ci.infra.status.im/job/website/job/docs.status.network/24/). Please return it and it will work.

I resolved a [merge conflict](https://github.com/status-im/status-network-docs/pull/3/commits/64eb5e648e3dec051556f3514ede31f5ea0e7a45#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R48) on my branch after the [force pushes](https://github.com/status-im/status-network-docs/compare/7a9a7f56d95565263d9e98385f78871235681c27..640798f1adb257ad425aed58b9d9e43f3fc8f1d3) from `master`, ig that's why.

I've pushed [the recommended fix](https://github.com/status-im/status-network-docs/pull/5/commits/75fc890562afc31f842b3177836a36f2edc23e17) to `master`. Please check if the CI is fixed @markoburcul since the docs hasn't updated after 15 mins.

**Comment by markoburcul** [comment]
> I've pushed [the recommended fix](https://github.com/status-im/status-network-docs/pull/5/commits/75fc890562afc31f842b3177836a36f2edc23e17) to `master`. Please check if the CI is fixed [@markoburcul](https://github.com/markoburcul) since the docs hasn't updated after 15 mins.

It is fixed

**Comment by nadeemb53** [comment]
its updated!
thanks @markoburcul @jakubgs 
I'll close the issue now

**Comment by jakubgs** [comment]
Don't you want to also deploy `develop` branch to `dev-docs.status.network` and use `master` only when the changes are ready?

**Comment by jakubgs** [comment]
It's pretty much a standard.

**Comment by nadeemb53** [comment]
please go ahead, we'll use it
